name: mcdavidhendersondrawing.com
favicon: null
layout_spectrum: 0.6393072954379022
typography_spectrum: 0.7038930365815759
title: drawing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5eedc'
    - '#e4dccf'
    - '#989294'
    - '#c3b9af'
    - '#696270'
  brandStrength: 0.5625
  lightness: 0.03685179934836924
  saturation: 0.4808349625673145
  rhythmicContrast: 0.464477785397321
purpose: []
